package Vista;

import jade.gui.GuiAgent;
import jade.gui.GuiEvent;

public class frm_Controles extends javax.swing.JFrame {

    private GuiAgent gui;

    public frm_Controles(GuiAgent gui) {
        this.gui = gui;
        initComponents();
        setBounds(0, 0, 300, 200);
        this.setLocationRelativeTo(null); // centrar ventana
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_Izquierda = new javax.swing.JButton();
        btn_Derecha = new javax.swing.JButton();
        btn_Girar = new javax.swing.JButton();
        lbl_Titulo = new javax.swing.JLabel();
        lbl_Mensaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btn_Izquierda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Izquierda.png"))); // NOI18N
        btn_Izquierda.setText("Izquierda");
        btn_Izquierda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_IzquierdaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Izquierda);
        btn_Izquierda.setBounds(10, 50, 130, 41);

        btn_Derecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Derecha.png"))); // NOI18N
        btn_Derecha.setText("Derecha");
        btn_Derecha.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_Derecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DerechaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Derecha);
        btn_Derecha.setBounds(140, 50, 130, 41);

        btn_Girar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Girar.png"))); // NOI18N
        btn_Girar.setText("Girar");
        btn_Girar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GirarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Girar);
        btn_Girar.setBounds(90, 100, 110, 41);

        lbl_Titulo.setFont(new java.awt.Font("Tahoma", 1, 14));
        lbl_Titulo.setText("Controles Tetris Agentes");
        getContentPane().add(lbl_Titulo);
        lbl_Titulo.setBounds(40, 10, 180, 17);

        lbl_Mensaje.setFont(new java.awt.Font("Tahoma", 1, 12));
        lbl_Mensaje.setForeground(new java.awt.Color(204, 0, 0));
        lbl_Mensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Mensaje.setText("No se ha encontrado juego registrado!");
        getContentPane().add(lbl_Mensaje);
        lbl_Mensaje.setBounds(10, 30, 240, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_IzquierdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_IzquierdaActionPerformed
        //  System.out.println(" LEFT ");
        GuiEvent  evento = new GuiEvent(this, 0);
        evento.addParameter("LEFT");
        this.gui.postGuiEvent(evento);
    }//GEN-LAST:event_btn_IzquierdaActionPerformed

    private void btn_DerechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DerechaActionPerformed
        //  System.out.println(" RIGHT ");
        GuiEvent  evento = new GuiEvent(this, 1);
        evento.addParameter("RIGHT");
        this.gui.postGuiEvent(evento);
    }//GEN-LAST:event_btn_DerechaActionPerformed

    private void btn_GirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GirarActionPerformed
        // System.out.println(" TURN 360 ");
        GuiEvent  evento = new GuiEvent(this, 2);
        evento.addParameter("TURN");
        this.gui.postGuiEvent(evento);
    }//GEN-LAST:event_btn_GirarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Derecha;
    private javax.swing.JButton btn_Girar;
    private javax.swing.JButton btn_Izquierda;
    private javax.swing.JLabel lbl_Mensaje;
    private javax.swing.JLabel lbl_Titulo;
    // End of variables declaration//GEN-END:variables

    public void setSinJuego(){
        lbl_Mensaje.setForeground(new java.awt.Color(204, 0, 0));
        lbl_Mensaje.setText("No se ha encontrado juego registrado!");
        btn_Izquierda.setEnabled(false);
        btn_Derecha.setEnabled(false);
        btn_Girar.setEnabled(false);
    }

    public void setJugando(){
        lbl_Mensaje.setForeground(new java.awt.Color(0, 0, 255));
        lbl_Mensaje.setText("Jugando!");
        btn_Izquierda.setEnabled(true);
        btn_Derecha.setEnabled(true);
        btn_Girar.setEnabled(true);
    }
    
}
